[package]
name = "vaporise"
version = "0.1.0"
edition = "2021"
authors = ["Muhammad Nauman Raza <devraza@skiff.com>"]
description = "A simple, featureful and blazingly fast memory-safe alternative to 'rm' written in Rust."
readme = "README.md"
license = "MIT"

[dependencies]
clap = { version = "4.5.2", features = ["derive"] }
colored = "2.1.0"

[[bin]]
name = "vpr"
path = "src/main.rs"
